# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    # Skip certain combinations
    ignore:
      - goos: linux
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - repository:
      owner: dphaener
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/dphaener/zellijinator
    description: "A powerful session manager for Zellij"
    license: "MIT"
    test: |
      system "#{bin}/zellijinator", "--version"
    dependencies:
      - name: zellij
        type: optional
    install: |
      bin.install "zellijinator"

nfpms:
  - id: packages
    package_name: zellijinator
    vendor: dphaener
    homepage: https://github.com/dphaener/zellijinator
    maintainer: Darin Haener <dphaener@gmail.com>
    description: "A powerful session manager for Zellij"
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    dependencies:
      - zellij
    bindir: /usr/bin