name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  build:
    needs: test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [amd64, arm64]
        exclude:
          - os: ubuntu-latest
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build
        run: |
          GOOS=$(go env GOOS) GOARCH=${{ matrix.arch }} go build -v -o zellijinator-${{ matrix.os }}-${{ matrix.arch }}
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zellijinator-${{ matrix.os }}-${{ matrix.arch }}
          path: zellijinator-${{ matrix.os }}-${{ matrix.arch }}